import Head from "next/head";

import { api } from "~/utils/api";
import { Navigation } from "./components/navigation";
import { Hero } from "./components/home/hero";
import { Posts } from "./components/home/posts";

export default function Home() {
    const hello = api.post.hello.useQuery({ text: "from tRPC" });

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="mx-auto mt-5 max-w-[95%] rounded-3xl bg-bg-hero">
                    <Navigation />
                    <Hero />
                </div>
                <div className="mx-auto mt-5 max-w-[95%] rounded-3xl">
                    <Posts />
                </div>
            </main>
        </>
    );
}
